### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by EvaBruch** [NoLegalTech/ammana#204]
Hola. 

Fabián cree que en algún momento ya se abrió la cuenta de Analyitics para Amanna. Si realmente está abierta, simplemente necesitamos que se autorice a: poliedricagencia@gmail.com y a mi: evabruch@alterwork.net

Si no estuviera abierta, necesitamos que se abra una cuenta de G. Analytics para Amanna y que se incorpore el Código de Seguimiento en su web, para luego autorizar a las personas mencionadas antes para poder ver la cuenta. 

Gracias!

**Comment by pepellou** [comment]
@EvaBruch 

Todo lo que sé es que Ammana usa una cuenta de Analytics con el código UA-113959294-1 desde el 12/2/2018

¿Puede Fabián comprobar si dicho tracking code se gestiona desde alguna cuenta suya?
(yo apostaría por fabianvalmol@gmail.com)

**Comment by EvaBruch** [comment]
Verificado. Autorizaciones hechas y tema cerrado. 

Gracias.
